# Generated by Django 5.2.8 on 2025-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional source MP4 file for background conversion.', null=True, upload_to='videos/'),
        ),
    ]
