# Generated by Django 5.2.8 on 2025-11-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Wird vom FFmpeg-Worker automatisch gesetzt.', null=True),
        ),
    ]
