# Generated by Django 5.2.8 on 2025-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_auto_20251128_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Wird vom FFmpeg-Worker automatisch gesetzt.', null=True),
        ),
    ]
